name: Pull Request Check
on:
  pull_request:
    paths:
      - "workflows/**"
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  copy-workflows:
    name: Copy to workflows
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          cmp --silent .github/workflows/reusable.yml workflows/reusable.yml || (echo "::error::When editing reusable workflows, update both workflows and .github/workflows" && exit 1)
